#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a custom HTTP response header X-Served-By

# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

for config in /etc/nginx/sites-enabled/*; do
    if ! grep -q "X-Served-By" "$config"; then
        sed -i "/location \/ {/a\\
\t\tadd_header X-Served-By $HOSTNAME;" "$config"
    fi
done

service nginx restart
