#!/usr/bin/env bash
## This script installs and configures Nginx to serve a page containing 'Holberton School'
#
#set -e
#
## Install nginx
#apt-get update -y
#apt-get install -y nginx
#
## Ensure nginx is running
#service nginx start || service nginx restart
#
## Configure the default index page
#echo "Holberton School for the win!" | tee /var/www/html/index.html > /dev/null
