#!/usr/bin/env bash
# Installs and configures Nginx to serve a page with "Holberton School"

# Install nginx
apt-get update -y
apt-get install nginx -y

# Create custom HTML page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure nginx is running
service nginx start
